title: Imke
logo: # "/images/logo.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Education
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  <br><br>
  Grabe, I., & Zhu, J. (2023). Hidden Layer Interaction: A Co-Creative Design Fiction for Generative Models. Workshop on Generative AI and HCI. CHI ’23, Hamburg, Germany. http://arxiv.org/abs/2304.00266
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
